### ISSUE TITLE
qml: menu not showing

### ISSUE THREAD

**Issue by gwenzek** [limetext/support#5]
Hey, I'm interested in contributing.
But I'm surprised by the look of the qml frontend versus the code.

For instance in [main.qml](https://github.com/limetext/lime-qml/blob/master/main/main.qml#L22) there is a menu bar.
But when I launch it, I don't have any menus (it's neither on the top of the screen like for other linux app).
![lime](https://cloud.githubusercontent.com/assets/5920036/10554108/c2de2b72-7460-11e5-864d-a25663750d51.png)

Is this normal ?

As a warmup task I wanted to try to replace the 'xx' and 'yy' in the status bar by the actual coordinates.
Do you think it's a good start, or it may reveal harder than it looks like ?

**Comment by zoli** [comment]
Hi

About the menu its not normal the menu was showing before I'll look at that later and about the status bar i think you are starting at good point because you can get help from https://github.com/limetext/lime/issues/487 also there was an issue for qml to in https://github.com/limetext/lime/issues/486 and the code for the termbox front end is [here](https://github.com/limetext/lime-termbox/blob/master/main/main.go#L289-L331).

**Comment by zoli** [comment]
This is not a support issue you can open this in lime-qml repo.

**Comment by gwenzek** [comment]
thanks, I reopened it at:  limetext/lime-qml#14
